# Generated by Django 4.0.5 on 2023-02-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Duelo',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
